ALTER TABLE "WorkScheduleEmployee"
ADD COLUMN "allowanceAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "lateMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "earlyLeaveMinutes" INTEGER NOT NULL DEFAULT 0;
